### ISSUE TITLE
bug: cmd+up also moves the object up instead of changing order

### ISSUE THREAD

**Issue by TBD** [ricardo-crespo/Irakasi_project#2]

**Comment by ricardo-crespo** [comment]
Yes, I have to go much deeper with shortcuts. I haven't think much about them yet.
 @TBD Do you find customizing shortcuts an important feature?

**Comment by TBD** [comment]
yeah - need to be able to select my own shortcuts to fit my workflow

**Comment by ricardo-crespo** [comment]
This will take a while. I will try to:
- Centralize better the shortcut definition so no duplication is possible
- Set up a system for shortcut customization

**Comment by TBD** [comment]
I like VSCode system 
- it allows duplication of keyboard shortcuts depending on where are triggered
- filter actions
- easy rebinding (click on keyboard shortcut, press combo, done) 

<img width="1235" alt="image" src="https://github.com/user-attachments/assets/bb98a26d-0257-4656-a0bc-faa42dfcaa6a">

**Comment by ricardo-crespo** [comment]
Revamped all shortcuts system to avoid collisions and allow contexts. Prepared everything for shortcut customization in the future
